{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0f06136b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-10-06 22:10:31.158 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:31.162 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.596 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\zubair.hanif\\AppData\\Roaming\\Python\\Python313\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-10-06 22:10:32.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:32.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.390 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.414 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:33.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\zubair.hanif\\AppData\\Local\\Temp\\ipykernel_18228\\2133139961.py:65: FutureWarning: \n",
      "\n",
      "Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\n",
      "\n",
      "  sns.countplot(data=rfm, x='segment', palette='viridis', ax=ax)\n",
      "2026-10-06 22:10:33.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:34.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:34.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:34.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:34.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.246 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-10-06 22:10:35.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-10-06 22:10:35.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "st.set_page_config(page_title=\"Customer Segmentation RFM\", layout=\"wide\")\n",
    "st.title(\"Customer Segmentation - RFM Analysis\")\n",
    "st.caption(\"Segment customers into Champions, Loyal, At Risk, Lost\")\n",
    "\n",
    "uploaded_file = st.file_uploader(\"Upload sales CSV (date, customer_id, sales)\", type=[\"csv\"])\n",
    "\n",
    "def generate_sample():\n",
    "    rng = np.random.default_rng(42)\n",
    "    customers = [f\"CUST_{i:04d}\" for i in range(1, 501)]\n",
    "    rows = []\n",
    "    for cust in customers:\n",
    "        orders = rng.integers(1, 15)\n",
    "        for _ in range(orders):\n",
    "            date = datetime.now() - timedelta(days=int(rng.integers(1, 400)))\n",
    "            sales = float(rng.integers(20, 1000))\n",
    "            rows.append({\"date\": date, \"customer_id\": cust, \"sales\": sales})\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "if uploaded_file:\n",
    "    df = pd.read_csv(uploaded_file)\n",
    "    df['date'] = pd.to_datetime(df['date'], errors='coerce')\n",
    "else:\n",
    "    st.info(\"No file uploaded - using sample data (500 customers)\")\n",
    "    df = generate_sample()\n",
    "\n",
    "# RFM Calculation\n",
    "snapshot_date = df['date'].max() + timedelta(days=1)\n",
    "rfm = df.groupby('customer_id').agg(\n",
    "    recency=('date', lambda x: (snapshot_date - x.max()).days),\n",
    "    frequency=('date', 'count'),\n",
    "    monetary=('sales', 'sum')\n",
    ").reset_index()\n",
    "\n",
    "# Scoring 1-5\n",
    "rfm['r_score'] = pd.qcut(rfm['recency'], 5, labels=[5,4,3,2,1]).astype(int)\n",
    "rfm['f_score'] = pd.qcut(rfm['frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(int)\n",
    "rfm['m_score'] = pd.qcut(rfm['monetary'], 5, labels=[1,2,3,4,5]).astype(int)\n",
    "rfm['rfm_score'] = rfm['r_score']*100 + rfm['f_score']*10 + rfm['m_score']\n",
    "\n",
    "def segment(row):\n",
    "    if row['r_score'] >=4 and row['f_score'] >=4: return \"Champions\"\n",
    "    elif row['r_score'] >=3 and row['f_score'] >=3: return \"Loyal\"\n",
    "    elif row['r_score'] <=2 and row['f_score'] >=3: return \"At Risk\"\n",
    "    else: return \"Lost / Hibernating\"\n",
    "rfm['segment'] = rfm.apply(segment, axis=1)\n",
    "\n",
    "# KPIs\n",
    "c1,c2,c3,c4 = st.columns(4)\n",
    "c1.metric(\"Total Customers\", f\"{len(rfm)}\")\n",
    "c2.metric(\"Champions\", f\"{len(rfm[rfm['segment']=='Champions'])}\")\n",
    "c3.metric(\"Avg Monetary\", f\"${rfm['monetary'].mean():,.0f}\")\n",
    "c4.metric(\"At Risk\", f\"{len(rfm[rfm['segment']=='At Risk'])}\")\n",
    "\n",
    "# Charts\n",
    "left,right = st.columns(2)\n",
    "with left:\n",
    "    fig, ax = plt.subplots(figsize=(8,4))\n",
    "    sns.countplot(data=rfm, x='segment', palette='viridis', ax=ax)\n",
    "    ax.set_title(\"Customers by Segment\")\n",
    "    plt.xticks(rotation=20)\n",
    "    st.pyplot(fig)\n",
    "with right:\n",
    "    fig, ax = plt.subplots(figsize=(8,4))\n",
    "    sns.scatterplot(data=rfm, x='recency', y='monetary', hue='segment', palette='viridis', ax=ax)\n",
    "    ax.set_title(\"Recency vs Monetary\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "st.dataframe(rfm.sort_values('monetary', ascending=False).head(10), use_container_width=True)\n",
    "st.download_button(\"Download RFM\", rfm.to_csv(index=False), \"rfm_segments.csv\", \"text/csv\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
